# Generated by Django 4.1.2 on 2022-10-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celeryApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenerateFileLog',
        ),
    ]
